services:
  webscraping-manager:
    build: webscraping-manager
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    container_name: webscraping-manager
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    env_file:
      - .env
    volumes:
      - .:/webscraping-manager
    ports:
      - "80:8080"
    depends_on:
      - auth-service
      - notification-service
      - webscraping-service
      - db


  auth-service:
    build: auth-service
    container_name: auth-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/auth-service
    ports:
      - "3000:3000"
    depends_on:
      - db

  notification-service:
    build: notification-service
    container_name: notification-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    env_file:
      - .env
    volumes:
      - .:/notification-service
    ports:
      - "3002:3002"
    depends_on:
      - db


  webscraping-service:
    build: webscraping-service
    container_name: webscraping-service
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0' && bundle exec rails sidekiq"
    env_file:
      - .env
    volumes:
      - .:/webscraping-service
    ports:
      - "3001:3001"
    depends_on:
      - db


  redis:
    image: redis:8.2-alpine 
    container_name: redis-server
    command: redis-server
    ports:
      - '6379:6379'

  db:
    image: postgres:14-trixie  
    restart: always
    environment:
      POSTGRES_PASSWORD: 72b7bd77613227b903ed8d7ee1792c69
      POSTGRES_DB: postgres
      POSTGRES_USER: alisson
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5431:5432"


